version: '3'
services:
    client: 
        build:            
            context: ./client
        ports:            
            - '3333:3000'        
        environment: 
            - REACT_APP_API_URL=http://localhost:5001/api 
        depends_on:            
            - server
        volumes:            
            - ./client:/app/             
            - /app/node_modules
    server:
        build:            
            context: ./server            
        ports:
            - '5001:5000'
        environment:        
            - PGDATABASE=postgres            
            - PGHOST=db             
            - PGPASSWORD=password
            - PGUSER=postgres
        depends_on:             
            - db
        volumes:            
            - ./server:/app            
            - /app/node_modules                     
    db:
        build:            
            context: ./db        
        volumes: 
            - form-volume:/var/lib/postgresql/data
        ports:            
            - '5433:5432'
volumes:     
    form-volume: